server:
  port: 8087
 
spring:
  application:
    name: nutrition-config-server
 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nikhilrdy2203/config-server-properties.git
          clone-on-start: true
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
